### ISSUE TITLE
Clarification on ./INTEGRATION_SANDBOX_SFDX_URL.auth File Configuration

### ISSUE THREAD

**Issue by neozhu** [Szandor72/devops-center-actions#2]
![image](https://github.com/Szandor72/devops-center-actions/assets/1549611/450d5bb5-02cd-43e0-a82e-7d4e5809f32e)

Hello,

I'm currently integrating the `devops-center-actions` into my project but facing an issue with configuring the `./INTEGRATION_SANDBOX_SFDX_URL.auth` file. I am unsure about where to define the content for this file, the correct format to use, and the specific path within the repository where it should be placed. Due to this, I am unable to successfully run the workflow as intended.

Could you please provide detailed guidance on:
1. The expected format and content for the `./INTEGRATION_SANDBOX_SFDX_URL.auth` file.
2. The recommended repository path where this file should be saved.
3. Any additional setup or configuration steps required to ensure the workflow runs smoothly with this file.

Your assistance in resolving this issue would be greatly appreciated, as it would help me utilize the `devops-center-actions` more effectively in my project.

Thank you.

**Comment by Szandor72** [comment]
Hello neozhu,

the files in question are created on the fly and populated with information from [github secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository) which you will need to provide. 

`INTEGRATION_SANDBOX_SFDX_URL` secret will contain the value of the `Sfdx Auth Url` when running the command `sf org display --verbose --target-org YOUR_TARGET_ORG`. The auth url starts with `force://`

From the Readme:

> Configure the Actions to use your own Orgs and Secrets
${{ secrets.PROD_DEVOPS_CENTER_HOME_SFDX_URL }} will be used to query DevOps Center records and create a package.xml file to do deployment validation with exactly the same metadata as DevOps Center would use. Note: Deleted components are not validated.
${{ secrets.INTEGRATION_SANDBOX_SFDX_URL }} will be used to do test deployments and CSV Scan Report File Upload

**Comment by neozhu** [comment]
Thanks for the help! Problem solved.
